const DATABASES_BASE_ROUTE = '/databases'

const DATABASES_ROUTE = {
  QUERY: `${DATABASES_BASE_ROUTE}/query`,
  CREATE: `${DATABASES_BASE_ROUTE}/create`,
  UPDATE: `${DATABASES_BASE_ROUTE}/update`,
}

export { DATABASES_BASE_ROUTE, DATABASES_ROUTE }
